import type { Metadata } from "next";
import Header from "@/components/v2/Header";
import Footer from "@/components/v2/Footer";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Header />
      <div className="bg-[#F6F2EC]">

        {children}
      </div>
      <Footer />
    </div>
  );
}
